name: Clone Hugging Face repo

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone Hugging Face repo
      run: |
        git clone https://huggingface.co/ShinojiResearch/Senku-70B-Full
        cd Senku-70B-Full
        git remote add origin https://github.com/empereurpirate/Empereur.git
        git push origin master

